name: CI

on: [push]

jobs:
  test-php81:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer, phpunit
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: composer install
      - name: Run unit tests
        run: vendor/bin/phpunit
      - name: Run PHPCS check
        run: vendor/bin/phpcs --report-full --standard=PSR12 src
      - name: Run phpstan check
        run: vendor/bin/phpstan analyse

  test-php82:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer, phpunit
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: composer install
      - name: Run unit tests
        run: vendor/bin/phpunit
      - name: Run PHPCS check
        run: vendor/bin/phpcs --report-full --standard=PSR12 src
      - name: Run phpstan check
        run: vendor/bin/phpstan analyse
